# Generated by Django 2.1.3 on 2018-11-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_banner',
            field=models.ImageField(blank=True, upload_to='image/banner'),
        ),
    ]
