# Generated by Django 2.1.3 on 2018-11-06 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_project_image_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_banner',
            field=models.ImageField(upload_to='image/banner/'),
        ),
    ]
