# Generated by Django 2.1.3 on 2018-11-06 04:30

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20181106_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='color_top_header_menu',
            field=colorfield.fields.ColorField(default='#FF0000', max_length=18),
        ),
    ]
