# Generated by Django 2.1.3 on 2018-11-06 04:39

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_color_top_header_menu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='color_top_header_menu',
        ),
        migrations.AddField(
            model_name='project',
            name='background_content_block',
            field=colorfield.fields.ColorField(default='#FCCD0E', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='background_footer',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='background_header_menu',
            field=colorfield.fields.ColorField(default='#FCCD0E', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='background_top_header',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='color_content_block',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='color_footer',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='color_header_menu',
            field=colorfield.fields.ColorField(default='#000000', max_length=18),
        ),
        migrations.AddField(
            model_name='project',
            name='color_top_header',
            field=colorfield.fields.ColorField(default='#ffffff', max_length=18),
        ),
    ]
